"""empty message

Revision ID: 35291c8315b4
Revises:
Create Date: 2020-05-30 01:46:15.300787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35291c8315b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_movie_association',
                    sa.Column('actor_id', sa.Integer, sa.ForeignKey('actors.id')),
                    sa.Column('movie_id', sa.Integer, sa.ForeignKey('movies.id'))
                    )
    
    op.create_table('movies',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('release_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('actors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('gender', sa.String(), nullable=True),
                    sa.Column('movie_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actors')
    op.drop_table('movies')
    # ### end Alembic commands ###
